# Generated by Django 5.2.17 on 2026-09-21 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_backlogs', models.PositiveIntegerField(blank=True, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_departments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='skills.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'skill'), name='unique_job_required_skill')],
            },
        ),
    ]
